### ISSUE TITLE
STRG + C

### ISSUE THREAD

**Issue by ForberichN** [arnecls/ga-PR340#1]
![grafik](https://user-images.githubusercontent.com/18482518/36696311-22916bce-1b44-11e8-9d98-6733ffb2adb8.png)
Control C wirft eine exception bevor onSignal ausgeführt wird.

**Comment by arnecls** [comment]
Schaue ich mir an. Aber ein paar Fragen vorneweg:

- Was passiert wenn du die exception ignorierst?
- Kannst du den Callstack posten (markieren und copy/paste sollte gehen)
- Welche Visual Studio und Windows Version hast du da?

**Comment by ForberichN** [comment]
Nach der exception wird onSignal normal ausgefürt. Wird der Server auserhalb von visual studio gestartet wird der server normal beendet.
Ich nutze Visual studio 2017 mit allen updates.
![grafik](https://user-images.githubusercontent.com/18482518/36739472-4db5d212-1be0-11e8-97a8-288940d205fd.png)

**Comment by arnecls** [comment]
Ah - dann ist das ein Feature von Visual Studio das man abschalten kann. Also kein Bug, sondern nur ein nerviger default von VS. In der Community edition scheint mir das Menü dafür entweder zu fehlen oder die haben es mal wieder verschoben. Wenn ich mich recht erinnere war das unter `Debug -> Exceptions`. Dann gab es da eine lange Liste mit Exception-Typen die man an- und aus schalten kann. Ich meine man konnte auch irgendwie über den exception code auf den Typ kommen und dann ausschalten.
Aber leider kann ich das hier nicht nachvollziehen und dir damit keine genauere Anleitung geben.
Im Zweifel - einfach ignorieren und weiter drücken.

**Comment by arnecls** [comment]
Das hier sollte helfen: https://msdn.microsoft.com/de-de/library/x85tt0dd.aspx

`Debuggen -> Fenster -> Ausnahmeeinstellungen`

Und wenn ich das richtig sehe kannst du die in dem Dialog der bei dir aufpopped auch direkt ausschalten.
